= ¡Da color a tu terminal!
:published_at: 2015-11-23
:hp-tags: ANSI escape code,color,tput
:hp-alt-title: Colores en tu terminal

¿Te gustaría escribir y leer textos coloreados en tu terminal? ¿Necesitas que tus programas impriman mensajes de advertencia o error coloreados? ¡Este es tu post! +

El texto en la terminal se puede clasificar en función de la paleta de colores que utiliza:

- *ASCII plano:* monocromático. Es el texto típico.

- *Colores ANSI:* es una paleta de ocho colores. Soportada por casi todas las terminales.

- *Colores de 8 bits:* es una paleta de 256 colores. Soportada por la mayoría de las terminales.

- *Color de 24 bits o color verdadero:* es una paleta de más de 16 millones de colores. Soportada por pocas terminales (por ejemplo, _Konsole_ o _UXterm_).

A continuación explicaremos como utilizar las diferentes paletas de colores. Para imprimir textos puedes utilizar el comando *_printf_* (no imprime un salto de línea, *_\n_* al final) o el comando *_echo -e_* (sí imprime un salto de línea al final).

== Colores ANSI

A continuación describiremos el esquema general que hay que seguir para imprimir textos coloreados, independientemente de la paleta de colores que se utilice:

```bash
"\x1b[1;XYmTEXTO\x1b[0m"
```

*o*

```bash
"\033[1;XYmTEXTO\033[0m"
```

- *_\x1b[_* o *_\033[_*. Estos caracteres son obligatorios al principio del código de color. Indican que se va a utilizar un carácter ANSI.

- *_1;_*. *Es opcional*. Indica que el color a utilizar es *brillante*. Elimínalo si quieres un color *normal*.

- *_X_*. Indica si el color que se va a cambiar es del texto o el del fondo.

[cols="2*"]
|===
|X |Significado

|3 |Color del texto
|4 |Color del fondo
|===

Se pueden combinar:

```bash
"\x1b[1;3Y;1;4YmTEXTO\x1b[0m"
```
El *_1;3Y_* indica el color del texto y el *_1;4Y_* el color del fondo.

- *_Y_*. Selecciona el color.

[cols="2*"]
|===
|Y |Significado

|0 |[black_silver]*Negro*
|1 |[red_silver]*Rojo*
|2 |[green_silver]*Verde*
|3 |[yellow_silver]*Amarillo*
|4 |[blue_silver]*Azul*
|5 |[magenta_silver]*Magenta*
|6 |[cyan_silver]*Cian*
|7 |[white_silver]*Blanco*
|8 |[black]*Otro.* Se utiliza para indicar *colores de 8 bits y de 24 bits*.
|===

- *_m_*. Indica el final del código de color.

- *_TEXTO_*. El texto que quieres colorear. Se pueden insertar en él tantos códigos de color como se quiera. Si un código de color cambiar el color del texto pero no el color del fondo, el color del texto se reemplaza por el nuevo color pero el del fondo no, y viceversa.

- *_\x1b[0m_*. Devuelve el texto a sus colores por defecto.

Ejemplo:

```bash
echo -e "\x1b[1;31m [red]*ESTO ES ROJO BRILLANTE*\x1b[42m CON FONDO VERDE NORMAL\x1b[0m"
```

El siguiente _script_ en _Bash_ muestra las diferentes combinaciones de colores ANSI:

```bash
#!/bin/bash
T='Texto'
echo -e "\n                 40m     41m     42m     43m     44m     45m     46m     47m";
for FGs in '    m' '   1m' '  30m' '1;30m' '  31m' '1;31m' '  32m' '1;32m' '  33m' '1;33m' '  34m' '1;34m' '  35m' '1;35m' '  36m' '1;36m' '  37m' '1;37m';
  do FG=${FGs// /}
  echo -en " $FGs \033[$FG  $T  "
  for BG in 40m 41m 42m 43m 44m 45m 46m 47m;
    do echo -en "$EINS \033[$FG\033[$BG  $T \033[0m\033[$BG \033[0m";
  done
  echo;
done
echo
```
Este _script_ se ha modificado a partir del _script_ original de _Daniel Crisman_ (ver link:http://www.tldp.org/HOWTO/Bash-Prompt-HOWTO/x329.html[aquí]; licencia link:http://www.gnu.org/copyleft/fdl.html[GFDL]) 

Guardalo como *_ANSI_colors_* y ejecutalo así:

```bash
chmod +x ./ANSI_colors
./ANSI_colors
```

Estos colores también se pueden imprimir con *_tput_*:

- *tput setaf Y*. Indica el color del texto.

- *tput setab Y*. Indica el color del fondo.

- *tput sgr0*. Devuelve el color del texto y del fondo a sus valores por defecto.

Puedes seguir el siguiente esquema para imprimirlos así:

```bash
echo -e "$(tput setaf Y)$(tput setab Y)TEXTO$(tput sgr0)"
```

Ejemplo:

```bash
echo -e "$(tput setaf 1) ESTO ES ROJO $(tput setab 2) CON FONDO VERDE $(tput sgr0)"
```

El siguiente _script_ muestra las combinaciones de colores que puede imprimir *tput*:


```bash
#!/bin/bash
echo " B0  B1  B2  B3  B4  B5  B6  B7 "
for af in {0..7}
do
  for ab in {0..7}
  do
    printf "$(tput setaf $af)$(tput setab $ab) F$af "
  done
  echo "$(tput sgr0)"
done
```
Guardalo como *_tput_colors_* y ejecutalo así:

```bash
chmod +x ./tput_colors
./tput_colors
```

== Colores de 8 bits

Siguen el siguiente esquema:

```bash
"\x1b[1;X8;5;ZZZmTEXTO\x1b[0m"
```
Donde:

- *_X_*: 3 para el color del texto, 4 para el del fondo.

- *_5;_*: indica que la paleta de colores que se va a utilizar es de 8 bits.

- *_ZZZ_*: es un número de 0 a 255 que indica el color dentro de la paleta.

El siguiente _script_ muestra los 256 colores de esta paleta:

```bash
#!/bin/bash
echo -en "\n   +  "
for i in {0..35}; do
  printf "%2b " $i
done

printf "\n\n %3b  " 0
for i in {0..15}; do
  echo -en "\033[48;5;${i}m  \033[m "
done

#for i in 16 52 88 124 160 196 232; do
for i in {0..6}; do
  let "i = i*36 +16"
  printf "\n\n %3b  " $i
  for j in {0..35}; do
    let "val = i+j"
    echo -en "\033[48;5;${val}m  \033[m "
  done
done

echo -e "\n"
```
Este _script_ se ha modificado a partir del _script_ original de _Michael Plotke_ (ver link:http://bitmote.com/index.php?post/2012/11/19/Using-ANSI-Color-Codes-to-Colorize-Your-Bash-Prompt-on-Linux[aquí]; licencia link:http://creativecommons.org/licenses/by/3.0/[CC BY]) 

== Colores de 24 bits 

Siguen el siguiente esquema:

```bash
"\x1b[1;X8;2;RRR;GGG;BBBmTEXTO\x1b[0m"
```
Donde:

- *_X_*: 3 para el color del texto, 4 para el del fondo.

- *_2;_*: indica que la paleta de colores que se va a utilizar es de 24 bits.

- *_RRR_*: es un número de 0 a 255 que indica la cantidad de rojo que contendrá el color seleccionado.

- *_GGG_*: es un número de 0 a 255 que indica la cantidad de verde que contendrá el color seleccionado.

- *_BBB_*: es un número de 0 a 255 que indica la cantidad de azul que contendrá el color seleccionado.
        
Para seleccionar colores en esta paleta puedes utilizar la heramienta online link:http://www.w3schools.com/tags/ref_colorpicker.asp[HTML Color Picker] de link:http://www.w3schools.com/[W3Schools].

