= Cómo crear alias de tu usuario
:published_at: 2015-11-24
:hp-tags: usuario,contraseña
:hp-alt-title: Añade sinónimos de tu nombre de usuario

En ocasiones resulta cómodo disponer de alias para tu usuario. Por ejemplo, cuando quieres acceder a un servidor por _SSH_ escribes:

```bash
ssh <usuario>@<servidor>
```
Si tu nombre de usuario coincide en el cliente y en el servidor, puedes simplificarlo así:

```bash
ssh <servidor>
```
Puede parecer un detalle sin importancia, pero cuando tienes que acceder a ese servidor decenas de veces al día la cosa cambia. Un alias puede hacer tu vida un poco más cómoda :-)

Para crear un alias debes pertenecer al grupo _sudo_ y seguir los siguientes pasos. Si no perteneces al grupo _sudo_, un administrador debe hacerlo por ti.

== Crear un alias

*1. Editar el fichero _/etc/passwd_:*

Busca la línea que empieza por el nombre de tu usuario y copiala. Edita la línea copiada, sustituyendo el nombre de usuario por el alias:

```bash
usuario:x:100N:100N:Nombre y Apellidos,,,:/home/usuario:/bin/bash
alias:x:100N:100N:Nombre y Apellidos,,,:/home/usuario:/bin/bash
```
*NO* edites la ruta de tu home en la línea del alias ni ningún otro dato, salvo que tengas claro lo que estás haciendo ;-)

*2. Editar el fichero _/etc/shadow_:*

Haz lo mismo que con el otro fichero.

```bash
usuario:TU CONTRASEÑA ENCRIPTADA:NNNNN:0:99999:7:::
alias:TU CONTRASEÑA ENCRIPTADA:NNNNN:0:99999:7:::
```

*3. Editar el fichero _/etc/group_:*

Aquí tendrás que hacer dos cosas:

- Lo mismo que con los dos ficheros anteriores:

```bash
usuario:x:100N:
alias:x:100N:
```
- Añadir el alias a todos los grupos en los que esté tu usuario. Por ejemplo, editamos esta línea:

```bash
migrupo:x:27:usuario,otro_usuario,y_otro,y_otro_mas ...
```
Para que quede así:

```bash
migrupo:x:27:usuario,alias,otro_usuario,y_otro,y_otro_mas ...
```

*4. Editar el fichero _/etc/gshadow_:*

Haz lo mismo que con _/etc/group_. +


¡Ya puedes utilizar tu alias! Prueba a identificarte con tu alias (la contraseña es la misma que la de tu usuario) y ejecuta el comando _who_. Verás que te devuelve el alias. Cómo se trata de un alias, tendrás exactamente los mismos permisos que con tu usuario. Por ejemplo, podrás editar cualquier fichero de tu usuario si accedes con tu alias y viceversa. De hecho, tu usuario y tu alias son el mismo usuario porque comparten *_UID_* (identificador de usuario) y, por tanto, el propietario de estos ficheros es el mismo.